services:
  backend:
    build: ./backend
    environment:
      SQLITE_PATH: /app/data/kpi_builder.sqlite
      PORT: 3001
      NODE_ENV: production
    volumes:
      - ./backend/data:/app/data
    ports:
      - "3001:3001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3001/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3


