services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kpi_builder
      POSTGRES_USER: kpi_user
      POSTGRES_PASSWORD: kpi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kpi_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://kpi_user:kpi_password@postgres:5432/kpi_builder
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3001/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:


