// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxbqczazcjhnltlzaeyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4YnFjemF6Y2pobmx0bHphZXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTkzMzMsImV4cCI6MjA3NTMzNTMzM30.LD5QbwTNtnMwbk8nwWpbNqzEOzA_iMl0UJvXmpoSbSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});